config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :books

  get 'transactions', to: 'transactions#index'

  root 'books#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/transact.rb
class Transact < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_query

    def set_query
        @query = Book.ransack(params[:q])
        @book = @query.result(distinct: true)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @query = Book.ransack(params[:q])
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_path
    else
      render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to books_path
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
    def book_params 
      params.require(:book).permit(:judulBuku, :namaPengarang, :penerbit, :tahunTerbit)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  def index
    @transactions = Transaction.all
    @query = Book.ransack(params[:q])
  end

  def show
  end

  def new
    @transaction = Transaction.new
  end

  def edit
  end

  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def transaction_params
      params.require(:transaction).permit(:name, :book_title, :purchase_date, :shipped_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/transacts_helper.rb
module TransactsHelper
end

app/views/books/edit.html.erb
<%= render 'shared/navigation' %>
<p>
<%= render 'shared/form' %>

app/views/books/index.html.erb
<%= render 'shared/navigation' %>

<div class="container">
  <div class="row">
    <h1 class="text-center"><%= pluralize(@book.count, "Result" )%></h1>
    <p>
    <table class="table table-bordered table-hover table-responsive">
      <thead>
        <tr>
          <th> <strong>judul Buku</strong> </th>
          <th> <strong>Nama Pengarang</strong> </th>
          <th> <strong>Penerbit</strong> </th>
          <th> <strong>Tahun Terbit</strong> </th>
          <th class="text-center">Aksi</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td><%= book.judulBuku %></td>
            <td><%= book.namaPengarang %></td>
            <td><%= book.penerbit %></td>
            <td><%= book.tahunTerbit %></td>
            <td class="text-center">
              <%= link_to 'Edit', edit_book_path(book), class: 'btn btn-success' %>
              <%= link_to 'Delete', books_path(book), method: :delete, data: {confirm: 'Data Dihapus ? '}, class: 'btn btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="d-grid gap-2 d-md-block">
      <%= link_to 'Tambah Data Library  ', new_book_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<%= render 'shared/navigation' %>
<%= render 'shared/form' %>

app/views/books/show.html.erb
<%= render 'shared/navigation' %>

<div class="container">
  <div class="row">
    <%= form_for(@book) do |book| %>

        <div class="form-group">
          <%= book.label :Judul_Buku %>
          <%= book.text_field :judulBuku, class:'form-control', type: 'text', placeholder: 'Judul Buku', disabled: true %>
        </div>

        <div class="form-group">
          <%= book.label :Nama_Pengarang %>
          <%= book.text_field :namaPengarang, class:'form-control', type: 'text', placeholder: 'Nama Pengarang', disabled: true %>
        </div>

        <div class="form-group">
          <%= book.label :Penerbit %>
          <%= book.text_field :penerbit, class:'form-control', type: 'text', placeholder: 'Penerbit', disabled: true %>
        </div>

        <div class="form-group">
          <%= book.label :Tahun_Terbit %>
          <%= book.text_field :tahunTerbit, class:'form-control', type: 'number', placeholder: 'Tahun Terbit', disabled: true %>
        </div>

    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestErb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
<div class="container">
  <div class="row">
    <%= form_for(@book) do |book| %>

        <div class="form-group">
          <%= book.label :Judul_Buku %>
          <%= book.text_field :judulBuku, class:'form-control', type: 'text', placeholder: 'Judul Buku' %>
        </div>

        <div class="form-group">
          <%= book.label :Nama_Pengarang %>
          <%= book.text_field :namaPengarang, class:'form-control', type: 'text', placeholder: 'Nama Pengarang' %>
        </div>

        <div class="form-group">
          <%= book.label :Penerbit %>
          <%= book.text_field :penerbit, class:'form-control', type: 'text', placeholder: 'Penerbit' %>
        </div>

        <div class="form-group">
          <%= book.label :Tahun_Terbit %>
          <%= book.text_field :tahunTerbit, class:'form-control', type: 'number', placeholder: 'Tahun Terbit' %>
        </div>
        <br>
        <%= book.submit :Save, class:'btn btn-success' %>

    <% end %>
  </div>
</div>

app/views/shared/_formtransact.html.erb
<div class="container">
  <div class="row">
    <%= form_for(@tp) do |transact| %>

        <div class="form-group">
          <%= transact.label :Nama_Peminjam %>
          <%= transact.text_field :np, class:'form-control', type: 'text', placeholder: 'Judul Buku' %>
        </div>

        <div class="form-group">
          <%= transact.label :Buku_Pinjma %>
          <%= transact.text_field :bp, class:'form-control', type: 'text', placeholder: 'Nama Pengarang' %>
        </div>

        <div class="form-group">
          <%= transact.label :tgl_pinjam %>
          <%= transact.text_field :tgl_pinjam, class:'form-control', type: 'text', placeholder: 'Penerbit' %>
        </div>

        <div class="form-group">
          <%= transact.label :tgl_pengembalian %>
          <%= transact.text_field :tgl_pengembalian, class:'form-control', type: 'number', placeholder: 'Tahun Terbit' %>
        </div>

        <div class="form-group">
          <%= transact.label :Status_pengembalian %>
          <%= transact.text_field :status, class:'form-control', type: 'number', placeholder: 'Tahun Terbit' %>
        </div>
        <br>
        <%= transact.submit :Save, class:'btn btn-success' %>

    <% end %>
  </div>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Library</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="transactions">transact</a>
        </li>
      </ul>
      <div>
          <%= search_form_for(@query, url: books_path, method: :get, class:'d-flex' ) do |f| %>
          <%= f.search_field :judulBuku_or_namaPengarang_or_penerbit_or_tahunTerbit_i_cont_any, placeholder: "Search...", 
          class: "form-control me-2" %>
          <%= f.submit "Search", class:"btn btn-outline-succsee" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :book_title, style: "display: block" %>
    <%= form.text_field :book_title %>
  </div>

  <div>
    <%= form.label :purchase_date, style: "display: block" %>
    <%= form.datetime_field :purchase_date %>
  </div>

  <div>
    <%= form.label :shipped_at, style: "display: block" %>
    <%= form.datetime_field :shipped_at %>
  </div>
  <p>
  <div>
    <%= form.submit :Save, class:'btn btn-success' %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<p id="<%= dom_id transaction %>">
<table class="table table-bordered table-hover table-responsive">
  <thead>
      <tr>
        <th> <strong>Nama</strong> </th>
        <th> <strong>Buku</strong> </th>
        <th> <strong>Tanggal Pinjam</strong> </th>
        <th> <strong>Tanggal Jatuh Tempo</strong> </th>
      </tr>
  </thead>
      <tbody>
      <tr>
        <td> <%= transaction.name %> </td>
        <td> <%= transaction.book_title %> </td>
        <td> <%= transaction.purchase_date %> </td>
        <td> <%= transaction.shipped_at %> </td>
        </tr>
      </tbody>
    </table>
</p>

app/views/transactions/edit.html.erb
<%= render 'shared/navigation' %>
<p>
<div class= "container">
  <h1>Edit Data Transaksi</h1>
    <%= render "form", transaction: @transaction %>
    <br>
  <div>
    <%= link_to "Show this transaction", @transaction, class: "btn btn-primary" %> |
    <%= link_to "Back to transactions", transactions_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/transactions/index.html.erb
<%= render 'shared/navigation' %>
<div class= "container">
<p style="color: green"><%= notice %></p>
<h1>Data Peminjaman</h1>
<div id="transactions">
    <% @transactions.each do |transaction| %>
    <%= render transaction %>
    <p>
      <%= link_to "Show this transaction", transaction, class:'btn btn-primary' %>
    </p>
  <% end %>
</div>

<%= link_to "New transaction", new_transaction_path, class:'btn btn-success' %>
</div>

app/views/transactions/new.html.erb
<%= render 'shared/navigation' %>
  <div class= "container">
    <h1>Tambah Peminjaman</h1>
    <%= render "form", transaction: @transaction %>
    <br>
  <div>
    <%= link_to "Back to transactions", transactions_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render 'shared/navigation' %>
<div class= "container">
  <%= render @transaction %>
    <div>
      <%= link_to "Edit this transaction", edit_transaction_path(@transaction), class:'btn btn-primary'  %> |
      <%= link_to "Back to transactions", transactions_path, class:'btn btn-primary' %>
      <p>
      <%= button_to "Destroy this transaction", @transaction, method: :delete, class:'btn btn-danger' %>
    </div>
</div>